name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
        ndk-version: 25.1.8937393
        cmake-version: 3.22.1
        
    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-
          
    - name: Install dependencies
      run: bun install
      
    - name: Setup Expo CLI
      run: bun add --global @expo/cli
      
    - name: Cache Expo prebuild
      uses: actions/cache@v4
      with:
        path: |
          android
          .expo
        key: ${{ runner.os }}-expo-android-${{ hashFiles('app.json', 'package.json') }}
        restore-keys: |
          ${{ runner.os }}-expo-android-
          
    - name: Set environment variables
      run: |
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
        
    - name: Accept Android SDK licenses
      run: |
        mkdir -p $ANDROID_HOME/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-preview-license
      
    - name: Clean previous builds
      run: |
        rm -rf android
        rm -rf .expo
        rm -rf node_modules/.cache
        
    - name: Prebuild Android
      run: |
        export EXPO_NO_TELEMETRY=1
        export EXPO_NO_DOTENV=1
        export CI=1
        bunx expo prebuild --platform android --clean --no-install
      env:
        EXPO_NO_DOTENV: 1
        CI: 1
        EXPO_NO_TELEMETRY: 1
        
    - name: Install Android dependencies
      run: |
        cd android
        if [ -f "package.json" ]; then
          bun install
        fi
      
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          android/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('android/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Build APK
      run: |
        cd android
        export GRADLE_OPTS="-Xmx3g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.jvmargs=-Xmx3g"
        ./gradlew assembleRelease --no-daemon --stacktrace --info --build-cache
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
        ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
        CI: true
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
        
    - name: Build AAB (for Play Store)
      run: |
        cd android
        export GRADLE_OPTS="-Xmx3g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.jvmargs=-Xmx3g"
        ./gradlew bundleRelease --no-daemon --stacktrace --info --build-cache
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
        ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
        CI: true
        
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: android-aab
        path: android/app/build/outputs/bundle/release/app-release.aab
        if-no-files-found: error


