name: Build Expo App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: bun install
      
    - name: Setup Expo CLI
      run: bun add -g @expo/cli
      
    - name: Prebuild Android
      run: bunx expo prebuild --platform android --clean
      
    - name: Build APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleRelease
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Build AAB (for Play Store)
      run: |
        cd android
        ./gradlew bundleRelease
        
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: android-aab
        path: android/app/build/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Setup Expo CLI
      run: bun add -g @expo/cli
      
    - name: Prebuild iOS
      run: bunx expo prebuild --platform ios --clean
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build iOS
      run: |
        cd ios
        xcodebuild -workspace *.xcworkspace -scheme * -configuration Release -destination generic/platform=iOS -archivePath ./build/App.xcarchive archive
        xcodebuild -exportArchive -archivePath ./build/App.xcarchive -exportPath ./build -exportOptionsPlist ../export-options.plist
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: ios/build/*.ipa

  build-web:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Setup Expo CLI
      run: bun add -g @expo/cli
      
    - name: Export Web
      run: bunx expo export --platform web
      
    - name: Upload Web Build
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: dist/
